In [2]:
import os
from PIL import Image
import numpy as np
import cv2
import pickle

BASE_DIR = os.path.dirname(os.path.abspath("PycharmProject"))
image_dir = os.path.join(BASE_DIR, "Images")

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_alt.xml")

recognizer = cv2.face.LBPHFaceRecognizer_create()
recognizer.read("trainer.yml")

current_id = 0
label_ids = {}
x_train = []
y_labels = []

for root, dirs, files in os.walk(image_dir):
    for file in files:
        if file.endswith("png") or file.endswith("jpg") or file.endswith("jfif"):
            path = os.path.join(root, file)
            label = os.path.basename(os.path.dirname(path)).replace(" ", "-").lower()
            print(label,path)
            
            if not label in label_ids:
                label_ids[label] = current_id
                current_id += 1
            id_ = label_ids[label]
            print(label_ids)
            
            pil_image = Image.open(path).convert("L")
            image_array = np.array(pil_image, "uint8")
            print(image_array)
            
            faces = face_cascade.detectMultiScale(image_array,1.5,5)
            
            for (x,y,w,h) in faces:
                region_of_interest = image_array[y:y+h, x:x+w]
                x_train.append(region_of_interest)
                y_labels.append(id_)
                
with open("labels.pickle", "wb") as f:
    pickle.dump(label_ids, f)
    
recognizer.train(x_train, np.array(y_labels))
recognizer.save("trainer.yml")


akash C:\Users\adas0\PycharmProjects\Face_Recognition\Images\akash\FB_IMG_1575327207709.jpg
{'akash': 0}
[[176 181 176 ... 166 164 182]
 [181 184 175 ... 164 165 184]
 [186 187 175 ... 153 169 193]
 ...
 [170 164 128 ... 204 206 216]
 [163 169 139 ... 217 217 216]
 [147 164 144 ... 213 222 219]]
akash C:\Users\adas0\PycharmProjects\Face_Recognition\Images\akash\FB_IMG_1575327214159.jpg
{'akash': 0}
[[ 50  52  50 ...  32  27  23]
 [ 51  53  51 ...  31  26  22]
 [ 50  53  53 ...  30  25  21]
 ...
 [ 75  77  84 ... 186 171 126]
 [ 80  83  92 ... 200 195 107]
 [ 85  88  95 ... 200 195 107]]
akash C:\Users\adas0\PycharmProjects\Face_Recognition\Images\akash\FB_IMG_1575327222161.jpg
{'akash': 0}
[[248 248 248 ... 248 248 248]
 [248 248 248 ... 248 248 248]
 [248 248 248 ... 248 248 248]
 ...
 [248 248 248 ... 248 248 248]
 [248 248 248 ... 248 248 248]
 [248 248 248 ... 248 248 248]]
akash C:\Users\adas0\PycharmProjects\Face_Recognition\Images\akash\FB_IMG_1575327237600.jpg
{'akash': 0}
[[10